In [1]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [24]:
p1g = pd.read_csv('Plant_1_Generation_Data.csv')
p1g['DATE_TIME'] = pd.to_datetime(p1g['DATE_TIME'], format='%d-%m-%Y %H:%M')
p1g.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0

In [42]:
p1g[(p1g['DATE_TIME'].between('2020-05-20 22:45:00', '2020-05-21 07:45:00'))]

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
11752,2020-05-20 22:45:00,4135001,1BY6WEcLGh8j5v7,0.00,0.000,8249.00,6298346.00
11753,2020-05-20 22:45:00,4135001,1IF53ai7Xc0U56Y,0.00,0.000,8997.00,6225427.00
11754,2020-05-20 22:45:00,4135001,3PZuoBAID5Wc2HD,0.00,0.000,8982.00,7029494.00
11755,2020-05-20 22:45:00,4135001,7JYdWkrLSPkdwr4,0.00,0.000,8772.00,7643980.00
11756,2020-05-20 22:45:00,4135001,McdE0feGgRqW7Ca,0.00,0.000,8964.00,7201062.00
11757,2020-05-20 22:45:00,4135001,VHMLBKoKgIrUVDU,0.00,0.000,8982.00,7248524.00
11758,2020-05-20 22:45:00,4135001,WRmjgnKYAwPKWDb,0.00,0.000,8793.00,7069725.00
11759,2020-05-20 22:45:00,4135001,YxYtjZvoooNbGkE,0.00,0.000,8818.00,7221294.00
11760,2020-05-20 22:45:00,4135001,ZnxXDlPa8U1GXgE,0.00,0.000,8909.00,6564045.00
11761,2020-05-20 22:45:00,4135001,ZoEaEvLYb1n2sOq,0.00,0.000,8736.00,7139068.00
11762,2020-05-20 22:45:00,4135001,adLQvlD726eNBSB,0.00,0.000,9102.00,6313615.00
11763,2020-05-20 22:45:00,4135001,bvBOhCH3iADSZry,0.00,0.000,8131.00,6355038.00
11764,2020-05-20 22:45:00,4135001,iCRJl6heRkivqQ3,0.00,0.000,8887.00,7219605.00
11765,2020-05-20 22:45:00,4135001,ih0vzX44oOqAx2f,0.00,0.000,8664.00,6225941.00
11766,2020-05-20 22:45:00,4135001,pkci93gMrogZuBj,0.00,0.000,8849.00,7210198.00
11767,2020-05-20 22:45:00,4135001,rGa61gmuvPhdLxV,0.00,0.000,8821.00,7152633.00
11768,2020-05-20 22:45:00,4135001,sjndEbLyjtCKgGv,0.00,0.000,8777.00,7058061.00
11769,2020-05-20 22:45:00,4135001,uHbuxQJl8lW7ozc,0.00,0.000,8913.00,7080111.00
11770,2020-05-20 22:45:00,4135001,wCURE6d3bPkepu2,0.00,0.000,8895.00,6824244.00
11771,2020-05-20 22:45:00,4135001,z9Y9gH1T5YWrNuG,0.00,0.000,8796.00,7049261.00
11772,2020-05-20 22:45:00,4135001,zBIq5rxdHJRwDNY,0.00,0.000,8891.00,6380862.00
11773,2020-05-20 22:45:00,4135001,zVJPv84UY57bAof,0.00,0.000,8842.00,7157179.00
11774,2020-05-21 07:45:00,4135001,1BY6WEcLGh8j5v7,3946.25,387.775,296.25,6298642.25
11775,2020-05-21 07:45:00,4135001,1IF53ai7Xc0U56Y,3553.40,348.880,343.20,6225770.20
11776,2020-05-21 07:45:00,4135001,3PZuoBAID5Wc2HD,3534.60,347.020,342.20,7029836.20
11777,2020-05-21 07:45:00,4135001,7JYdWkrLSPkdwr4,3403.80,334.280,328.80,7644308.80
11778,2020-05-21 07:45:00,4135001,McdE0feGgRqW7Ca,3339.80,328.120,315.60,7201377.60
11779,2020-05-21 07:45:00,4135001,VHMLBKoKgIrUVDU,3504.60,344.080,338.00,7248862.00
11780,2020-05-21 07:45:00,4135001,WRmjgnKYAwPKWDb,3475.20,341.200,338.20,7070063.20
11781,2020-05-21 07:45:00,4135001,YxYtjZvoooNbGkE,3283.00,322.540,311.60,7221605.60
11782,2020-05-21 07:45:00,4135001,ZnxXDlPa8U1GXgE,4204.50,413.050,313.50,6564358.50
11783,2020-05-21 07:45:00,4135001,ZoEaEvLYb1n2sOq,4033.00,396.225,299.00,7139367.00
11784,2020-05-21 07:45:00,4135001,adLQvlD726eNBSB,3605.00,353.900,349.20,6313964.20
11785,2020-05-21 07:45:00,4135001,bvBOhCH3iADSZry,3109.20,305.540,298.20,6355336.20
11786,2020-05-21 07:45:00,4135001,iCRJl6heRkivqQ3,3257.00,320.000,309.40,7219914.40
11787,2020-05-21 07:45:00,4135001,ih0vzX44oOqAx2f,3278.00,322.080,311.20,6226252.20
11788,2020-05-21 07:45:00,4135001,pkci93gMrogZuBj,3171.80,311.640,300.20,7210498.20
11789,2020-05-21 07:45:00,4135001,rGa61gmuvPhdLxV,3203.60,314.760,302.20,7152935.20
11790,2020-05-21 07:45:00,4135001,sjndEbLyjtCKgGv,3255.60,319.860,308.60,7058369.60
11791,2020-05-21 07:45:00,4135001,uHbuxQJl8lW7ozc,4057.50,398.650,302.50,7080413.50
11792,2020-05-21 07:45:00,4135001,wCURE6d3bPkepu2,3253.00,319.600,304.00,6824548.00
11793,2020-05-21 07:45:00,4135001,z9Y9gH1T5YWrNuG,3321.00,326.280,312.60,7049573.60
11794,2020-05-21 07:45:00,4135001,zBIq5rxdHJRwDNY,3257.80,320.080,307.80,6381169.80
11795,2020-05-21 07:45:00,4135001,zVJPv84UY57bAof,3250.20,319.340,306.60,7157485.60

Отсутствуют данные по выработке энергии с 23:00 20 мая 2020 до 07:45 21 мая 2020

In [8]:
p1w = pd.read_csv('Plant_1_Weather_Sensor_Data.csv')
p1w['DATE_TIME'] = pd.to_datetime(p1w['DATE_TIME'], format='%Y-%m-%d %H:%M:%S')
p1w.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

In [47]:
p1_joined = p1w.merge(p1gg, on='DATE_TIME', how='inner')
p1_joined.head(50)

,DATE_TIME,PLANT_ID_x,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,PLANT_ID_y,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
5,2020-05-15 01:15:00,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
6,2020-05-15 01:30:00,4135001,HmiyD2TTLFNqkNe,24.638674,22.352926,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
7,2020-05-15 01:45:00,4135001,HmiyD2TTLFNqkNe,24.873022,23.160919,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
8,2020-05-15 02:00:00,4135001,HmiyD2TTLFNqkNe,24.936930,23.026113,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
9,2020-05-15 02:15:00,4135001,HmiyD2TTLFNqkNe,25.012248,23.343229,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
10,2020-05-15 02:30:00,4135001,HmiyD2TTLFNqkNe,25.005149,23.639459,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
11,2020-05-15 02:45:00,4135001,HmiyD2TTLFNqkNe,24.993020,24.039486,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
12,2020-05-15 03:00:00,4135001,HmiyD2TTLFNqkNe,25.016309,24.384136,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
13,2020-05-15 03:15:00,4135001,HmiyD2TTLFNqkNe,24.985215,24.351508,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
14,2020-05-15 03:30:00,4135001,HmiyD2TTLFNqkNe,24.937732,24.060297,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
15,2020-05-15 03:45:00,4135001,HmiyD2TTLFNqkNe,24.879100,23.709794,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
16,2020-05-15 04:00:00,4135001,HmiyD2TTLFNqkNe,24.678902,22.589942,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
17,2020-05-15 04:15:00,4135001,HmiyD2TTLFNqkNe,24.351931,21.783643,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
18,2020-05-15 04:30:00,4135001,HmiyD2TTLFNqkNe,24.062622,21.852525,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
19,2020-05-15 04:45:00,4135001,HmiyD2TTLFNqkNe,24.013224,22.306315,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
20,2020-05-15 05:00:00,4135001,HmiyD2TTLFNqkNe,24.177106,22.551908,0.000000,4135001,0.000000,0.000000,0.000000,6.852802e+06
21,2020-05-15 05:15:00,4135001,HmiyD2TTLFNqkNe,24.304888,22.979492,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
22,2020-05-15 05:30:00,4135001,HmiyD2TTLFNqkNe,24.328727,23.452380,0.000000,4135001,0.000000,0.000000,0.000000,6.837223e+06
23,2020-05-15 05:45:00,4135001,HmiyD2TTLFNqkNe,24.289211,23.096692,0.000863,4135001,0.000000,0.000000,0.000000,6.837223e+06
24,2020-05-15 06:00:00,4135001,HmiyD2TTLFNqkNe,24.088446,22.206757,0.005887,4135001,44.864229,4.329960,0.000000,6.837223e+06
25,2020-05-15 06:15:00,4135001,HmiyD2TTLFNqkNe,24.011635,22.353459,0.022282,4135001,292.481009,28.254223,2.917234,6.837226e+06
26,2020-05-15 06:30:00,4135001,HmiyD2TTLFNqkNe,23.976731,22.893282,0.049410,4135001,694.143398,67.281575,14.751353,6.852817e+06
27,2020-05-15 06:45:00,4135001,HmiyD2TTLFNqkNe,24.218990,24.442444,0.095394,4135001,1301.208604,126.838555,37.250271,6.852839e+06
28,2020-05-15 07:00:00,4135001,HmiyD2TTLFNqkNe,24.537398,27.185653,0.141940,4135001,1879.359740,184.211916,78.079545,6.852880e+06
29,2020-05-15 07:15:00,4135001,HmiyD2TTLFNqkNe,24.815960,28.888478,0.154713,4135001,2025.645833,198.578301,125.089827,6.852927e+06
30,2020-05-15 07:30:00,4135001,HmiyD2TTLFNqkNe,24.988790,29.605644,0.148799,4135001,1982.695076,194.360687,175.017045,6.852977e+06
31,2020-05-15 07:45:00,4135001,HmiyD2TTLFNqkNe,25.216180,29.547111,0.144793,4135001,2017.995130,197.822484,222.201299,6.853024e+06
32,2020-05-15 08:00:00,4135001,HmiyD2TTLFNqkNe,25.419513,31.412545,0.201639,4135001,2947.036526,289.345860,280.037338,6.853082e+06
33,2020-05-15 08:15:00,4135001,HmiyD2TTLFNqkNe,25.959082,35.528711,0.345708,4135001,4633.507143,454.639302,374.054870,6.853176e+06
34,2020-05-15 08:30:00,4135001,HmiyD2TTLFNqkNe,26.430782,40.318059,0.405349,4135001,5096.798431,499.800135,498.635823,6.853301e+06
35,2020-05-15 08:45:00,4135001,HmiyD2TTLFNqkNe,26.831830,39.081954,0.312427,4135001,4204.793831,412.730357,603.159903,6.853405e+06
36,2020-05-15 09:00:00,4135001,HmiyD2TTLFNqkNe,27.620970,45.009233,0.623153,4135001,7527.222403,736.879545,754.235390,6.853556e+06
37,2020-05-15 09:15:00,4135001,HmiyD2TTLFNqkNe,27.988362,46.617706,0.344884,4135001,4492.091721,440.583279,908.226461,6.853710e+06
38,2020-05-15 09:30:00,4135001,HmiyD2TTLFNqkNe,27.516728,39.136326,0.249248,4135001,3478.284091,341.427273,994.949675,6.853797e+06
39,2020-05-15 09:45:00,4135001,HmiyD2TTLFNqkNe,27.450108,40.930577,0.541206,4135001,7335.001623,717.868750,1115.153680,6.853917e+06
40,2020-05-15 10:00:00,4135001,HmiyD2TTLFNqkNe,28.632192,52.547736,0.670675,4135001,8319.373376,813.490828,1333.942370,6.854136e+06
41,2020-05-15 10:15:00,4135001,HmiyD2TTLFNqkNe,28.768913,47.633738,0.572283,4135001,7214.388799,705.997727,1498.797078,6.854300e+06
42,2020-05-15 10:30:00,4135001,HmiyD2TTLFNqkNe,29.351443,49.249723,0.455148,4135001,5868.347078,574.935990,1673.780682,6.854476e+06
43,2020-05-15 10:45:00,4135001,HmiyD2TTLFNqkNe,28.854708,44.048326,0.361962,4135001,5141.961039,504.164951,1809.058766,6.854611e+06
44,2020-05-15 11:00:00,4135001,HmiyD2TTLFNqkNe,29.410819,47.685453,0.636561,4135001,8807.637987,860.752695,1972.270617,6.854774e+06
45,2020-05-15 11:15:00,4135001,HmiyD2TTLFNqkNe,30.216062,50.006989,0.585787,4135001,7286.419372,712.896077,2170.580087,6.854972e+06
46,2020-05-15 11:30:00,4135001,HmiyD2TTLFNqkNe,30.287073,49.841364,0.557069,4135001,7064.052760,691.240179,2351.184253,6.855153e+06
47,2020-05-15 11:45:00,4135001,HmiyD2TTLFNqkNe,30.811049,47.836383,0.467987,4135001,7621.281656,745.526786,2512.323052,6.855315e+06
48,2020-05-15 12:00:00,4135001,HmiyD2TTLFNqkNe,31.305375,49.183584,0.514963,4135001,7082.804383,693.218561,2710.043020,6.855512e+06
49,2020-05-15 12:15:00,4135001,HmiyD2TTLFNqkNe,31.507298,49.844493,0.787866,4135001,9525.881765,930.773539,2906.013799,6.855709e+06

In [45]:
p1_joined[(p1_joined['DC_POWER'].isnull())]

Empty DataFrame
Columns: [DATE_TIME, PLANT_ID_x, SOURCE_KEY, AMBIENT_TEMPERATURE, MODULE_TEMPERATURE, IRRADIATION, PLANT_ID_y, DC_POWER, AC_POWER, DAILY_YIELD, TOTAL_YIELD]
Index: []

In [19]:
p1w.describe()

        PLANT_ID  AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION
count     3182.0          3182.000000         3182.000000  3182.000000
mean   4135001.0            25.531606           31.091015     0.228313
std          0.0             3.354856           12.261222     0.300836
min    4135001.0            20.398505           18.140415     0.000000
25%    4135001.0            22.705182           21.090553     0.000000
50%    4135001.0            24.613814           24.618060     0.024653
75%    4135001.0            27.920532           41.307840     0.449588
max    4135001.0            35.252486           65.545714     1.221652